version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"              # directory containing primary_requirements.txt
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
